apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpi-jax-train
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 20
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: <aws-acct-id>.dkr.ecr.us-east-1.amazonaws.com/axlearn_neuronx:latest
             name: mpitest
             imagePullPolicy: Always
             env:
               - name: POD_UID
                 valueFrom:
                  fieldRef:
                    fieldPath: metadata.uid
             command:
             - mpirun
             - --allow-run-as-root
             - -np
             - "4"  # should be equal to number of trn nodes
             - -bind-to
             - none
             - -map-by
             - slot
             - -x
             - POD_UID
             - -wdir
             - /neuron/axlearn/
             - /neuron/run_trainer_multinode.sh
           initContainers:
           - name: wait-hostfilename
             image: <aws-acct-id>.dkr.ecr.us-east-1.amazonaws.com/axlearn_neuronx:latest
             command:
             - bash
             - -cx
             - "[[ $(cat /etc/mpi/discover_hosts.sh | wc -l) != 1 ]] && (date; echo Ready; cat /etc/mpi/discover_hosts.sh) || (date; echo 'not ready ...'; sleep 5; exit 1) && while read host; do while ! ssh $host echo $host ; do date; echo \"Pod $host is not up ...\"; sleep 5; done; date; echo \"Pod $host is ready\"; done <<< \"$(/etc/mpi/discover_hosts.sh)\""
             volumeMounts:
             - mountPath: /etc/mpi
               name: mpi-job-config
             - mountPath: /root/.ssh
               name: ssh-auth

    Worker:
      replicas: 4  # should be equal to number of trn nodes
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                    - trn2n.48xlarge
          containers:
          - image: <aws-acct-id>.dkr.ecr.us-east-1.amazonaws.com/axlearn_neuronx:latest
            name: mpitest
            imagePullPolicy: Always
            resources:
              limits:
                aws.amazon.com/neuron: "16"
                vpc.amazonaws.com/efa: "64"
              requests:
                aws.amazon.com/neuron: "16"
                vpc.amazonaws.com/efa: "64"
            volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
